banuablasite/urls.py
from django.conf.urls import url, handler404, handler500, include
from django.urls import path
from django.contrib import admin
from banuabla import views
from django.conf.urls.static import static
from django.conf import settings


handler404 = views.handler404
handler500 = views.handler500


urlpatterns = [
    path("adminx/", admin.site.urls),
    path("kullanim-ve-gizlilik/", views.gizlilik, name="gizlilik"),
    path("sss/", views.sss, name="sss"),
    path("activate/", views.activate, name="activate"),
    path("activate/<uuid:activate_code>", views.activate, name="activate"),
    path("summernote/", include('django_summernote.urls')),
    path("blog/", include("blog.urls")),
    path("login/", views.login, name="login"),
    path("logout/", views.logout, name="logout"),
    path("register/", views.register, name="register"),
    path("forgotpasswd/", views.forgotpasswd, name="forgotpasswd"),
    path("forgotpasswd/<uuid:code>/", views.forgotpasswd, name="forgotpasswd_uuid"),
    path("panel/", views.panel, name="panel"),
    path("panel/<int:user_id>", views.panel, name="panel_user"),
    path("profile/", views.profile, name="profile"),
    path("order/", views.order, name="order"),
    path("order/<int:order_id>", views.order_detail, name="order_detail"),
    path("order/add/", views.order_add, name="order_add"),
    path("buy/", views.buy, name="buy"),
    path("buy/done", views.buy_done, name="buy_done"),
    path("comments/", views.comments, name="comments"),
    path("contact/", views.contact, name="contact"),
    path("OneSignalSDKWorker.js", views.onesignal),
    path("OneSignalSDKUpdaterWorker.js", views.onesignal),
    path("manifest.json", views.manifest),
    path("", views.home, name="home"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/urls.py
from django.conf.urls import url
from blog import views



urlpatterns = [
    url(r'^page/(?P<page>\d*)$', views.page, name="page_view"),
    url(r'^post/(?P<post_title>[\w-]+)\.html$', views.post_view, name="post_view"),
    url(r'^$', views.home, name="blog"),
]

banuabla/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager
import uuid
import time


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Süper kullanıcı için is_staff=True yapmalısınız.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Süper kullanıcı için is_superuser=True yapmalısınız.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    cinsiyet = (
        (None, "Cinsiyetinizi Seçiniz"),
        ("K", "Kadın"),
        ("E", "Erkek")
    )
    referanced_user = models.ForeignKey("User", verbose_name="Refansı", null=True, blank=True, default="", on_delete=models.CASCADE)
    user_photo = models.ImageField(verbose_name="Profil Fotoğrafı", upload_to="profil/", null=True, blank=True)
    fal_credit = models.IntegerField(verbose_name="Fal Baktırma Hakkı", default=0)
    fal_point = models.IntegerField(verbose_name="Fal Puanı", default=0)
    gender = models.CharField(max_length=1, verbose_name="Cinsiyeti", null=True, default=None, blank=True, choices=cinsiyet)
    birth = models.IntegerField(default=1900, verbose_name="Doğum Yılı")
    about = models.CharField(max_length=500, verbose_name="Hakkında", null=True, blank=True)
    login_ip = models.GenericIPAddressField(verbose_name="Son Giriş IP", null=True, blank=True)
    is_verify = models.BooleanField(default=False, verbose_name="Doğrulanmış")
    forgotcode = models.UUIDField(default=uuid.uuid4, editable=False)

    username = None
    email = models.EmailField(verbose_name="E-Posta", unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

    def save(self, *args, **kwargs):
        if self.fal_point >= 20:
            self.fal_point -= 20
            self.fal_credit += 1
        super().save(*args, **kwargs)

    def activate_code(self):
        return self.forgotcode

    def referanced_link(self):
        return self.id + 1024

    def full_name(self):
        return self.first_name + " " + self.last_name

    def __str__(self):
        return self.email

    class Meta:
        verbose_name_plural = "Kullanıcılar"


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Siparişi Veren")
    fal_yorumu = models.FileField(upload_to="fal-yorumu", verbose_name="Fal Yorumu", null=True)
    order_status = models.BooleanField(verbose_name="Sipariş Tamamlandı", default=False)
    order_date = models.DateTimeField(auto_created=True, auto_now_add=True, verbose_name="Sipariş Zamanı")

    def tahmini(self):
        sira = Order.objects.filter(order_status__exact=False, order_date__lt=self.order_date).count()

        if sira + time.localtime().tm_hour > 23:
            return "Ertesi Gün İçerisinde"
        else:
            return "Gün İçerisinde"

    def started(self):
        orders = Order.objects.filter(order_status__exact=False, order_date__lt=self.order_date)
        if not orders.count():
            return "Sıra Sizde"
        else:
            return "Sırada {} Fal Var".format(orders.count())

    def status(self):
        if self.order_status:
            return "Teslim Edildi"

        else:
            return "Teslim Edilmedi"

    def clean_fal_yorumu(self):
        return self.fal_yorumu.name.split("/")[-1]

    def __str__(self):
        return "{}-{}".format(self.user, self.id)

    class Meta:
        verbose_name_plural = "Fal Siparişleri"


class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Mesajın Sahibi")
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name="Hangi Sipariş")
    content = models.TextField(verbose_name="Mesaj İçeriği", max_length=1000)
    message_date = models.DateTimeField(auto_created=True, auto_now=True, verbose_name="Mesaj Zamanı")

    def __str__(self):
        return self.content[:25]

    class Meta:
        verbose_name_plural = "Fal Sipariş Mesajları"


class Image(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name="Sipariş")
    image = models.ImageField(verbose_name="Fotoğraf", upload_to="photo/")

    def clean_name(self):
        return self.image.name.split("/")[-1]

    def __str__(self):
        return self.image.name

    class Meta:
        verbose_name_plural = "Fal Fotoğrafları"


class Comments(models.Model):
    name = models.CharField(verbose_name="İsim", max_length=25)
    comment = models.CharField(verbose_name="Yorum", max_length=1024)

    def __str__(self):
        return self.comment

    class Meta:
        verbose_name_plural = "Müşteri Yorumları"


class BuyOrder(models.Model):
    x = ((1, "Tadımlık"), (3, "Meraklı"), (5, "Bağımlı"))
    y = ((0, "Beklemede"), (1, "Ödeme Geldi"))

    user = models.ForeignKey(User, verbose_name="Satın Alan", on_delete=models.CASCADE)
    date = models.DateTimeField(verbose_name="Sipariş Zamanı", auto_now_add=True)
    shopping_cart = models.IntegerField(verbose_name="Sepetteki Ürün", choices=x)
    buy_status = models.IntegerField(verbose_name="Sipariş Durumu", choices=y, default=0)
    readonly = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if self.buy_status and not self.readonly:
            self.readonly = True
            u = User.objects.get(email=self.user)
            u.fal_credit += self.shopping_cart
            u.save()
        super().save(*args, **kwargs)

    def __str__(self):
        return "SP"+str(self.id+1024)

    def sp_no(self):
        return "SP" + str(self.id + 1024)

    def price(self):
        cart = int(self.shopping_cart)
        if cart == 1:
            return "20₺"

        if cart == 3:
            return "55₺"

        if cart == 5:
            return "90₺"

    class Meta:
        verbose_name_plural = "Kredi Siparişi"

banuabla/forms.py
from django import forms
from banuabla.models import User


class ProfileForm(forms.Form):
    first_name = forms.CharField(max_length=50, label="Adın", required=False,
                                 widget=forms.TextInput(attrs={"class": "validate", "data-length": "50"}))
    last_name = forms.CharField(max_length=50, label="Soyadın", required=False,
                                widget=forms.TextInput(attrs={"class": "validate", "data-length": "50"}))
    birth = forms.IntegerField(label="Doğum Yılın", required=False, max_value=2018, min_value=1900,
                               widget=forms.NumberInput(attrs={"class": "validate", "data-length": "4"}))
    gender = forms.CharField(label="Cinsiyetin", required=False, widget=forms.Select(attrs={"class": "validate",
                                                                                            "data-length": "50"},
                                                                                     choices=User.cinsiyet))
    about = forms.CharField(max_length=500, label="Hakkınızda", label_suffix="", required=False,
                            widget=forms.Textarea(attrs={"class": "materialize-textarea", "data-length": "500"}))
    password = forms.CharField(max_length=50, label="Parola", required=False, min_length=6,
                               widget=forms.PasswordInput(attrs={"class": "validate", "data-length": "50"}))
    password2 = forms.CharField(max_length=50, label="Parola (tekrar)", required=False, min_length=6,
                                widget=forms.PasswordInput(attrs={"class": "validate", "data-length": "50"}))


class UploadForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ("user_photo",)


class ForgotpasswdForm(forms.Form):
    forgot_email = forms.EmailField(max_length=50, label="E-Posta", label_suffix="",
                                    widget=forms.EmailInput(attrs={"class": "validate", "data-length": "50"}))


class LoginForm(forms.Form):
    email = forms.EmailField(max_length=50, label="E-Posta", label_suffix="",
                            widget=forms.EmailInput(attrs={"class": "validate", "data-length": "50"}))
    password = forms.CharField(max_length=50, label="Parola", label_suffix="",
                               widget=forms.PasswordInput(attrs={"class": "validate", "data-length": "50"}))


class RegisterForm(forms.Form):
    user_email = forms.EmailField(max_length=50, label="E-Posta", label_suffix="", required=True,
                             widget=forms.EmailInput(attrs={"class": "validate", "data-length": "50"}))
    user_password = forms.CharField(max_length=50, min_length=6, label="Parola", label_suffix="",
                               widget=forms.PasswordInput(attrs={"class": "validate", "data-length": "50"}))
    user_password2 = forms.CharField(max_length=50, min_length=6, label="Parola (tekrar)", label_suffix="",
                                widget=forms.PasswordInput(attrs={"class": "validate", "data-length": "50"}))


class ContactForm(forms.Form):
    full_name = forms.CharField(max_length=50, label="Ad Soyad", label_suffix="",
                                widget=forms.TextInput(attrs={"class": "validate", "data-length": "50"}))

    guest_email = forms.EmailField(max_length=50, label="E-Posta", label_suffix="",
                             widget=forms.EmailInput(attrs={"class": "validate", "data-length": "50"}))

    subject = forms.CharField(max_length=50, label="Konu", label_suffix="",
                                widget=forms.TextInput(attrs={"class": "validate", "data-length": "50"}))

    message = forms.CharField(max_length=500, label="Mesajınız", label_suffix="",
                              widget=forms.Textarea(attrs={"class": "materialize-textarea", "data-length": "500"}))


class OrderAddForm(forms.Form):
    fal1 = forms.ImageField(required=False)
    fal2 = forms.ImageField(required=False)
    fal3 = forms.ImageField(required=False)
    fal4 = forms.ImageField(required=False)
    message = forms.CharField(widget=forms.Textarea(attrs={"class": "materialize-textarea", "data-length": "500"}),
                              required=False, label="Mesajınız", label_suffix="", max_length=500)


class OrderMessageForm(forms.Form):
    message = forms.CharField(widget=forms.Textarea(attrs={"class": "materialize-textarea", "data-length": "500"}),
                              max_length=500, label="Mesajınız", label_suffix="", required=False)
    sound = forms.FileField(required=False, label_suffix="", label="Fal Yorumu")




templates/banuabla/home.html
{% extends "banuabla/base.html" %}{% load static %}
{% block title %}Banu Abla'dan Çevirim içi Kahve Falı Baktırın.{% endblock %}
{% block head %}
    <link rel="canonical" href="{{ request.build_absolute_uri }}">
    <meta name="description" content="Gerçek birinden, yılların deneyimine sahip Banu Abla'dan kahve falı baktırın.">
    <meta name="keywords" content="türk kahvesi, kahve falı, fal baktır, gerçek kahve falı, kahve falı baktır">
    <meta name="robots" content="index, nofollow">
    <meta property="og:url" content="{{ request.build_absolute_uri }}">
    <meta property="og:title" content="Banu Abla'dan Çevirim içi Kahve Falı Baktırın.">
    <meta property="og:description" content="Gerçek birinden, yılların deneyimine sahip Banu Abla'dan kahve falı baktırın.">
    <meta property="og:image" content="{% static "image/bg.jpg" %}">

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-127953461-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-127953461-1');
    </script>
{% endblock %}
{% block body %}
    <header id="header" class="parallax-container">
        <div class="container">
            <div class="row">
                <div class="col l8 offset-l2 center m10 offset-m1">
                    <h2 class="white-text">Üç Vakte Kadar</h2>
                    <h5 class="white-text">Kahveni İç, Falını Kapat, Fotoğrafları Yolla</h5>
                    <a href="{% url "order_add" %}" class="btn btn-large green waves-effect waves-light">Fal Baktır</a>
                    <br><br>
                    <a target="_blank" href="https://www.facebook.com/share.php?u={{ request.build_absolute_uri }}"
                    class="btn waves-light waves-effect" style="background-color: #4267b2">
                        <i class="fab fa-facebook"></i> Paylaş
                    </a>
                    <a href="https://twitter.com/intent/tweet?text=Banu Abla'dan Çevirim içi Kahve Falı Baktırın. - {{ request.build_absolute_uri|iriencode }}"
                    class="btn waves-light waves-effect" style="background-color: #00aced" target="_blank">
                        <i class="fab fa-twitter"></i> Paylaş
                    </a>
                </div>
            </div>
        </div>
        <div class="parallax"><img src="{% static "image/bg.jpg" %}"></div>
    </header>

    <section id="how">
        <div class="container">
            <div class="row">
                <h2 class="center">Nasıl Çalışıyor</h2>
                <div class="col l4 m10 offset-m1">
                    <div class="card medium">
                        <div class="card-image">
                            <img src="{% static "image/kahve.jpg" %}">
                            <span class="card-title"><strong>Köpüklü Türk Kahveni İç</strong></span>
                        </div>
                        <div class="card-content">
                            <p>Köpüklü kahveni içtikten sonra tabağını üstüne kapatıp ters çevirin. Parmağınız ile fincanın tabanına
                            dokunduğunuz da ılık geldiyse fincanınız fal için hazırdır.</p>
                        </div>
                    </div>
                </div>

                <div class="col l4 m10 offset-m1">
                    <div class="card medium">
                        <div class="card-image">
                            <img src="{% static "image/tabak.jpg" %}">
                            <span class="card-title"><strong>Fincanın Fotoğraflarını Çekin</strong></span>
                        </div>
                        <div class="card-content">
                            <p>Soğuduktan sonra açtığınız fincanın tam üstten ışıklı bir ortamda
                                farklı açılardan fotoğraflarını çekiyorsun. Fincan tabağını da eğip akmış halinin fotoğrafını çekmeyi
                            unutmuyorsun.</p>
                        </div>
                    </div>
                </div>

                <div class="col l4 m10 offset-m1">
                    <div class="card medium">
                        <div class="card-image">
                            <img src="{% static "image/tabak.jpg" %}">
                            <span class="card-title"><strong>Falınızı Gönderin</strong></span>
                        </div>
                        <div class="card-content">
                            <p>Sipariş oluşturup çektiğiniz fotoğrafları ve varsa mesajınızı ekleyin ve siparişinizi gönderin.
                            Fal yorumunuz ses kaydı olarak oluşturduğunuz sipariş üzerinden gönderilecektir.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <section id="messages">
        <div class="container">
            <div class="row">
                <h2 class="center">Müşteri Yorumları</h2>
                <div id="comment-box" class="col l8 offset-l2 center m10 offset-m1">
                    <i class="fa fa-quote-left"></i>
                    <p id="comment">Ağzınıza sağlık umarım dediğiniz gibi olur, teşekkür ederim :)</p>
                    <i class="fa fa-quote-right"></i>
                    <p id="comment-writer">Edepali D.</p>
                </div>
            </div>
        </div>
    </section>

    <section>
        <div class="container">
            <div class="row">
                <div id="about" class="col l5 m10 offset-m1">
                    <h2 class="center">Hakkımda</h2>
                    <p>Doğma büyüme İstanbullu'yum. 1989 yılında Üsküdar Mithatpaşa Kız Teknik ve Meslek Lisesi Resim Bölümü'nü
                    bitirdikten sonra kısa bir dönem emlakçılık işiyle uğraştım. Bunun yanı sıra annemin ev toplantılarında
                    gelen misafirlerine annemden aldığım "el" ile kahve falına bakmaya başladım. Baktığım falların çoğunun
                    çıktığını görünce bu işi daha da ele aldım ve 25 seneden fazladır baktıran kişilerin ardı arkası kesilmedi.</p>
                    <p>2015 yılında Ankara'ya yerleştim ve o tarihten itibaren fal baktırmak isteyen arkadaşlarım WhatsApp ile fincan
                    fotoğraflarını attılar. Bu süreçte yaşımdan dolayı sürekli bir iş bulamadım. Bir gün eşimin bana "Seni bir siteye
                    üye yaptım orada şansını bir dene. Tutarsa sana bir site açarız." demesiyle bu işi meslek olarak ele almaya başladım.
                    Bu site üzerinde verdiğim <a href="https://www.sadeceon.com/ozbekbanu/kahve-faliniza-bakarim-">ilan</a>
                    ile yüzlerce kişiye fal yorumladım. Bu başarımdan dolayı eşim bu siteyi bana hediye
                    olarak sundu. Amacım ev ekonomisine katkı sağlamak ve insanları baktığım fallarla mutlu etmek.</p>
                </div>

                <div id="contact" class="col l5 offset-l2 m10 offset-m1">
                    <h2 class="center">Bana Ulaşın</h2>
                    <form id="contact_form" action="{% url "contact" %}" method="post">
                        {% csrf_token %}
                        <div class="input-field">
                            <i class="material-icons prefix">account_circle</i>
                            {{ contact_form.full_name }}
                            <label for="{{ contact_form.full_name.id_for_label }}">{{ contact_form.full_name.label }}</label>
                        </div>
                        <div class="input-field">
                            <i class="material-icons prefix">email</i>
                            {{ contact_form.guest_email }}
                            <label for="{{ contact_form.guest_email.id_for_label }}">{{ contact_form.guest_email.label }}</label>
                        </div>
                        <div class="input-field">
                            <i class="material-icons prefix">subject</i>
                            {{ contact_form.subject }}
                            <label for="{{ contact_form.subject.id_for_label }}">{{ contact_form.subject.label }}</label>
                        </div>
                        <div class="input-field">
                            <i class="material-icons prefix">message</i>
                            {{ contact_form.message }}
                            <label for="{{ contact_form.message.id_for_label }}">{{ contact_form.message.label }}</label>
                        </div>
                        <button id="contact_button" type="submit" class="btn green g-recaptcha waves-effect waves-light disabled" data-sitekey="6LfmEHIUAAAAAJUQ-E0GfZaGdxbQwrM6e6oOkB2j"
data-callback="onSubmit">Gönder</button>
                    </form>
                    {% if messages %}
                        {% for message in messages %}
                            {% if message.tags == "success" %}
                            <div class="card-panel green accent-4 white-text">
                                <i class="material-icons">check_circle</i><span>{{ message }}</span>
                            </div>{% else %}
                            <div class="card-panel red darken-4 white-text">
                                <i class="material-icons">error</i><span>{{ message }}</span>
                            </div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>
    </section>

{% endblock %}
{% block extrajs %}
    <script>
        function onSubmit(token) {
            document.getElementById("contact_form").submit();
        }

        $().ready(function () {
            $.getJSON("/comments/", function (comments) {
                var count = 1;
                var index = comments.length -1;

                setInterval(function () {

                    if(count !== index){
                        $("#comment").animate({
                            opacity: 0
                        }, "slow", function () {
                            $("#comment").html(comments[count]["comment"]).animate({
                            opacity: 1
                            });
                        });

                        $("#comment-writer").animate({
                            opacity: 0
                        }, "slow", function () {
                            $("#comment-writer").html(comments[count]["name"]).animate({
                            opacity: 1
                            });
                        });

                        ++count;

                    } else {
                        count = 0;
                        }

                }, 7000);

            });

            //iletişim formu
            $("#contact_form").keyup(function () {
                var full_name = $("#id_full_name").val().length;
                var guest_email =  $("#id_guest_email").val().length;
                var subject = $("#id_subject").val().length;
                var message = $("#id_message").val().length;

                if (full_name && guest_email && subject && message) {
                    $("#contact_button").removeClass("disabled");
                } else if (!$("#contact_button").hasClass("disabled")) {
                    $("#contact_button").addClass("disabled");
                }
            })
        });
    </script>

{% endblock %}

templates/banuabla/order_detail.html
{% extends "banuabla/base.html" %}{% load static banuablatags %}
{% block title %}Sipariş Detayı{% endblock %}
{% block head %}
{#    <link rel="stylesheet" href="{% static "css/order-detail.css" %}">#}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mediaelement/4.2.9/mediaelementplayer.min.css" />

{% endblock %}
{% block body %}
    <section id="order" class="container window">
        <h3 class="center-align">Sipariş Detayı</h3>
        {% if messages %}
        {% for message in messages %}
        <div class="col l10 offset-l1">
            {% if message.tags == "warning" %}
            <div class="card-panel yellow accent-4 white-text">
                <i class="material-icons">warning</i><span>{{ message }}</span>
            </div>
            {% elif message.tags == "error" %}
            <div class="card-panel red darken-4 white-text">
                <i class="material-icons">error</i><span >{{ message }}</span>
            </div>
            {% endif %}
        </div>
        {% endfor %}
        {% endif %}
        <h4 class="center-align">Gönderilen Fotoğraflar</h4>
        <div class="row">
            <div class="col l10 offset-l1">
                {% for fal_photo in fal_photos %}{% if not forloop.counter > 1 %}
                <div class="col l3">
                    <img src="{{ fal_photo.image.url }}" alt="{{ fal_photo.clean_name }}" class="responsive-img materialboxed">
                </div>{% endif %}{% if forloop.counter > 1 %}
                <div class="col l3">
                    <img src="{{ fal_photo.image.url }}" alt="{{ fal_photo.clean_name }}" class="responsive-img materialboxed">
                </div>{% endif %}
                {% endfor %}
            </div>
        </div>

        {% if order.fal_yorumu %}
        <h4 class="center-align">Fal Yorumunuz</h4>
        <div class="row">
            <div class="col l9 offset-l1">
                <audio preload="none" id="player" width="100%">
                    <source src="{{ order.fal_yorumu.url }}" type="audio/mpeg">
                </audio>
            </div>
            <div class="col l1">
                <a class="btn" href="{{ order.fal_yorumu.url }}" alt="{{ order.fal_yorumu.name }}" download>
                    <i class="fa fa-download"></i> İstersen İndir</a>
            </div>
        </div>
        {% endif %}

        {% if request.user.is_staff %}
        <h4 class="center-align">Gönderen Bilgisi</h4>
        <div class="row">
            <div class="col l10 offset-l1">
                <div class="card-panel white accent-4 black-text">{% now "Y" as current_year %}
                    <p>Ad Soyad: {{ order.user.full_name }}</p>
                    <p>Yaş: {{ current_year|sub:order.user.birth }}</p>
                    <p>Cinsiyet: {{ order.user.get_gender_display }}</p>
                    <p>Hakkında: {{ order.user.about|default:"Bilgi girilmemiş..." }}</p>
                </div>
            </div>
        </div>
        {% endif %}

        <h4 class="center-align">Konuşmalar</h4>

        <div class="row">
            <ul class="collection col l10 offset-l1">{% for message in order_messages %}
                <li class="collection-item avatar">
                    {% if message.user.user_photo %}
                    <img src="{{ message.user.user_photo.url }}" alt="{{ message.user.full_name }}" class="circle">{% else %}
                    <img src="{% static "image/empty_profile.jpg" %}" alt="{{ message.user.full_name }}" class="circle">{% endif %}
                    <a class="title" href="#!">{{ message.user.full_name }}</a>
                    <p>{{ message.content|escape|linebreaksbr }}</p>
                </li>
                {% endfor %}
            </ul>
        </div>


        <div class="row">
            <div class="col l10 offset-l1">
                <form id="order_form" action="{% url "order_detail" order.id %}" method="post" enctype="multipart/form-data">
                    {% csrf_token %}{% if request.user.is_staff %}
                    <div class="file-field input-field">
                        <div class="btn">
                            <span>{{ message_form.sound.label }}</span>
                            {{ message_form.sound }}
                        </div>
                        <div class="file-path-wrapper">
                            <input class="file-path validate" type="text">
                        </div>
                    </div>{% endif %}
                    <div class="input-field">
                        <i class="material-icons prefix">mode_edit</i>
                        {{ message_form.message }}
                        <label for="{{ message_form.message.id_for_label }}">{{ message_form.message.label }}</label>
                    </div>

                    <button type="submit" name="fal_gonder" class="btn green">
                        <i class="material-icons right">send</i> Mesaj Gönder
                    </button>
                    {% if not order.order_status and request.user.is_staff %}
                    <button type="submit" name="fal_teslim" class="btn green">Siparişi Tamamla</button>
                    {% endif %}
                </form>
            </div>
        </div>
    </section>


{% endblock %}
{% block extrajs %}
    <script src="https://cdnjs.cloudflare.com/ajax/libs/mediaelement/4.2.9/mediaelement-and-player.min.js"></script>
    <script>
        $(document).ready(function(){
            $('.materialboxed').materialbox();

            $('video, audio').mediaelementplayer();
        });
    </script>
{% endblock %}